version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: whitelabel_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_nova_senha # A mesma que você redefiniu antes
      POSTGRES_DB: whitelabel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Salva os dados para não perder se o contêiner cair

  backend:
    build:
      context: ./backend # Diz onde está o Dockerfile do back-end
    container_name: whitelabel_backend
    ports:
      - "4000:4000"
    environment:
      # O Node vai se conectar ao serviço "db" e não mais ao localhost
      DATABASE_URL: "postgresql://whitelabel_app:senha_da_api_123@db:5432/whitelabel"
    depends_on:
      - db # O back-end só sobe depois que o banco estiver pronto

  frontend:
    build:
      context: ./frontend # Diz onde está o Dockerfile do front-end
    container_name: whitelabel_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend # O front-end só sobe depois que o back-end estiver pronto

volumes:
  pgdata: